##七牛云的key
qiniu:
  accessKey: canKgBzqR_AN_EviuOuWYUT4Vko3gi5dTNZFiQ4C
  secretKey: feAWGHn_UmhGU2ckkHd9F2q2qFpC7lPqlemvEOCH
  bucketName: eumji025
  basePath: http://of8rkrh1w.bkt.clouddn.com/

## 百度推送
baidu:
  task:
    postUrl: http://data.zz.baidu.com/urls?site=www.eumji025.com&token=hHzO6TjfJBf4KA53
    baseUrl: http://www.eumji025.com

  thymeleaf:
    mode: HTML
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: wechat
server:
  session-timeout : 3600
  port: 8081
spring:
  mvc:
    favicon:
      enabled: false

